### ISSUE TITLE
beta15: caml/m.h not found on 32-bit pre-4.06.0 systems

### ISSUE THREAD

**Issue by aantron** [janestreet/jbuilder#311] opened 2017-11-06 00:08 UTC
[See this build log](https://ci.appveyor.com/project/aantron/lwt/build/765/job/99n64praik2wq6hu#L302):

```
#=== ERROR while installing jbuilder.1.0+beta15 ===============================#
# opam-version         1.2.2
# os                   cygwin
# command              ./boot.exe -j 4
# path                 /home/appveyor/.opam/system/build/jbuilder.1.0+beta15
# compiler             system (4.04.0)
# exit-code            1
# env-file             /home/appveyor/.opam/system/build/jbuilder.1.0+beta15/jbuilder-2488-629056.env
# stdout-file          /home/appveyor/.opam/system/build/jbuilder.1.0+beta15/jbuilder-2488-629056.out
# stderr-file          /home/appveyor/.opam/system/build/jbuilder.1.0+beta15/jbuilder-2488-629056.err
### stderr ###
# Error: exception Sys_error("/usr/lib/ocaml/caml/m.h: No such file or directory")
# Backtrace:
# Raised by primitive operation at file "pervasives.ml", line 366, characters 28-54
# Called from file "src/io.ml", line 45, characters 23-67
# Called from file "list.ml", line 135, characters 12-15
# Called from file "src/context.ml", line 313, characters 14-43
# Called from file "src/future.ml", line 83, characters 65-70
# Called from file "src/future.ml", line 37, characters 9-12
```

This is a new failure. Here's a recent log of beta14 being installed successfully: https://ci.appveyor.com/project/aantron/lwt/build/763/job/ojgdljd3n9ka0n4m#L350

This is with @fdopen's `opam-repository-mingw`.

**Comment by dra27** [comment] 2017-11-06 00:23
Thanks for the report - the log you've sent is not from a MinGW build (see the os line) - apart from anything else because beta15 is not in @fdopen's repo (yet).

The problem is a flaw in the new detection of 64-bit in #303. Because it doesn't find ARCH_SIXTYFOUR in config.h, it moves on to m.h which won't be there for a pre-4.06 system. It wasn't caught by CI because we only test 64-bit platforms.

@xclerc, @rgrinberg - I won't be back in work till Wednesday, would one of you be able to push a fix?

**Comment by aantron** [comment] 2017-11-06 00:27
I just noticed that and came to fix it, too :) It's an ordinary Cygwin build.

**Comment by xclerc** [comment] 2017-11-06 08:32
Sorry for the regression; here is a PR fixing it: https://github.com/janestreet/jbuilder/pull/313

**Comment by rgrinberg** [comment] 2017-11-06 09:22
Fixed by @xclerc

**Closed by rgrinberg** 2017-11-06 09:22 UTC
