### ISSUE TITLE
Only one of two test executables is picked up

### ISSUE THREAD

**Issue by keleshev** [janestreet/jbuilder#97] opened 2017-05-25 20:06 UTC
Just moved a small project to jbuilder, however only first test in the `deps` list is executed:

```scheme
(jbuild_version 1)

(executables
 ((names (test_version test_parsing))
  (libraries (semantic))))

(alias
 ((name    runtest)
  (deps    (test_version.exe test_parsing.exe))
  (action  (run ${<}))))
```

https://github.com/keleshev/semantic/blob/983c441335b3a2edf942da076aa1129848f809fc/test/jbuild#L9

**Comment by keleshev** [comment] 2017-05-25 20:27
Here's what I get running `jbuilder runtest`:

```
$ j runtest
    ocamldep test/test_version.depends.ocamldep-output
      ocamlc test/test_version.{cmi,cmo,cmt}
      ocamlc test/test_parsing.{cmi,cmo,cmt}
    ocamlopt test/test_parsing.{cmx,o}
    ocamlopt test/test_version.{cmx,o}
    ocamlopt test/test_version.exe
    ocamlopt test/test_parsing.exe
test_version alias test/runtest
test/test_version.ml
..........................................
```

Expected something like:

```
$ j runtest
    ocamldep test/test_version.depends.ocamldep-output
      ocamlc test/test_version.{cmi,cmo,cmt}
      ocamlc test/test_parsing.{cmi,cmo,cmt}
    ocamlopt test/test_parsing.{cmx,o}
    ocamlopt test/test_version.{cmx,o}
    ocamlopt test/test_version.exe
    ocamlopt test/test_parsing.exe
test_version alias test/runtest
test/test_version.ml
..........................................
test_parsing alias test/runtest
test/test_parsing.ml
........................
```

**Comment by rgrinberg** [comment] 2017-05-25 21:02
This is expected: See the docs for `${<}` http://jbuilder.readthedocs.io/en/latest/jbuild.html?highlight=special%20variables#variables-expansion

I'm not sure if you can run all dependencies the way you want in 1 alias. But you can simply write 2 aliases, 1 for each binary.

**Comment by diml** [comment] 2017-05-26 11:06
Closing this since it's the expected behavior.

Note that once I have finished the `meta-lang` branch, you be able to write:

```scheme
(:foreach %{x} (version parsing)
 (alias
  ((name    runtest)
   (deps    (test_%{x}.exe))
   (action  (run ${<}))))
```

**Closed** 2017-05-26 11:06 UTC
