### ISSUE TITLE
JBuilder doesn't relink exe file on macOS

### ISSUE THREAD

**Issue by artemkin** [janestreet/jbuilder#245] opened 2017-09-01 09:53 UTC
```
$ cat jbuild
(jbuild_version 1)

(executable
 ((name hello)))
$ echo 'let () = print_endline "Hello"' > hello.ml
$ jbuilder build hello.exe
    ocamldep hello.depends.ocamldep-output
      ocamlc hello.{cmi,cmo,cmt}
    ocamlopt hello.{cmx,o}
    ocamlopt hello.exe
$ ./_build/default/hello.exe
Hello
$ echo 'let () = print_endline "World"' > hello.ml
$ jbuilder build hello.exe
    ocamldep hello.depends.ocamldep-output
      ocamlc hello.{cmi,cmo,cmt}
    ocamlopt hello.{cmx,o}
$ ./_build/default/hello.exe
Hello
$ jbuilder clean
$ jbuilder build hello.exe
    ocamldep hello.depends.ocamldep-output
      ocamlc hello.{cmi,cmo,cmt}
    ocamlopt hello.{cmx,o}
    ocamlopt hello.exe
$ ./_build/default/hello.exe
World
```

Need to run `jbuilder clean` to get `hello.exe` updated. Experiencing this issue on macOS Sierra 10.12.5.

```
$ ocaml --version
The OCaml toplevel, version 4.05.0
$ opam --version
1.2.2
$ opam info jbuilder | grep "installed-version"
   installed-version: 1.0+beta12 [system]
```

**Comment by rdavison** [comment] 2017-09-01 13:03
I think this issue would be fixed by this Pull Request, if I'm not mistaken: https://github.com/janestreet/jbuilder/pull/238

**Comment by rgrinberg** [comment] 2017-09-01 16:59
Yup this is a duplicate of #237

**Closed by rgrinberg** 2017-09-01 16:59 UTC
