### ISSUE TITLE
How to use normal ppx rewriters?

### ISSUE THREAD

**Issue by rgrinberg** [janestreet/jbuilder#14] opened 2017-03-02 07:36 UTC
I see the following passage in the manual:

```
You are however free to use ppx rewriters that are not based on ppx_driver in
this list, since ppx_driver is able to import rewriters that where not
designed for ppx_driver.
```
But I'm not sure how to enable things like `js_of_ocaml.ppx` for example. As the only preprocessors that seem to work are jane street's.

Would be nice to update the quickstart manual with an example for this as well by the way. Some non jane street preprocessors are quite common.

**Comment by diml** [comment] 2017-03-02 08:49
Actually there is a required feature in `ppx_driver` that is not yet released to be able to do this. I'll update the manual.

In general, I expect that nobody would be happy to add `ppx_driver` as a dependency given that it has quite a lot of dependencies itself. So it would be nice to support ppx rewriters without requiring `ppx_driver`.

However, I'd like to keep things fast and I'm not very keen on the idea of running n sub-processes per file just to do the pre-processing. Especially now that ppx rewriters are migrating to `ocaml-migrate-parsetree` we are starting to do way too much work just for the pre-processing.

It would be very easy to write a tiny driver that sets `Ast_mapper.register_function`. What would be even more interesting is to group the various rewriters per version of the AST they use and do the minimum number of AST migration. This could be easily done by setting the various `Ast_XXX.Ast_mapper.register_function` references. Once we have such a tool it would be simple to adapt jbuilder to use it.

/cc @let-def who might be interested in this

**Comment by rgrinberg** [comment] 2017-03-02 08:53
I'm content with using ppx_driver so I can wait for it to be updated. But to confirm, there will be no support for normal `-ppx` flags?

**Comment by let-def** [comment] 2017-03-02 08:55
Interesting question. I started working on something related just this morning.

The problem is that Ast_mapper maintains some global state, and that state is using the current compiler-libs version.
My current approach is to migrate on the fly (when calling run_main / register, I lift the function and calls the main compiler implementation). This prevent regrouping rewriters by compiler version.

What you suggest is to have each version register one "meta" rewriting function that applies all version-specific rewriters?

There are also ppx_cookies to maintain. Right now the conversion is done on each read/write, but I don't think this can be avoided sanely.

**Comment by diml** [comment] 2017-03-02 09:39
@rgrinberg I'd rather not, no

@let-def, that's what I imagined. Do you think we could have a better API that would give more control to such a driver? What we could do is provide this new API, and only  ppx rewriters using it could be merged. The other ones would still be converted on the fly. People would have to switch to the new API in order to make their rewriter fast.

**Comment by let-def** [comment] 2017-03-02 11:30
@diml yes, it would be good to redesign the API.

Am I right to consider that the only two features to be covered are passing the parsetree through all rewriters, transparently migrating versions, and threading a "state" in the form of cookies, that have to be transparently rewritten too?

**Comment by diml** [comment] 2017-03-02 12:09
That seems correct to me

**Comment by diml** [comment] 2017-03-07 13:41
ocaml-migrate-parsetree now has a driver and jbuilder uses it instead of ppx_driver. In order to use ordinary ppx rewriters with jbuilder, they will have to be ported to ocaml-migrate-parsetree. I updated the manual accordingly

**Closed by diml** 2017-03-07 13:41 UTC

**Comment by adrieng** [comment] 2017-03-30 02:57
Would it be possible to amend the manual to make it even clearer that normal ppx drivers are **not** supported in any form? As a casual user of ppx syntax extensions, I was actually confused by the *Using a custom ppx driver* section.
