### ISSUE TITLE
sexpression backtrace exposed to toplevel

### ISSUE THREAD

**Issue by avsm** [janestreet/jbuilder#396] opened 2018-01-06 17:11 UTC
I got this with a typo in jbuilder beta16:

```
$ jbuilder build
Error: exception Usexp__Parser_automaton_internal.Error.Parse_error(_)
Backtrace:
Raised at file "vendor/usexp/src/parser_automaton_internal.ml", line 165, characters 4-45
Called from file "vendor/usexp/src/parser_automaton_internal.ml", line 372, characters 31-76
Called from file "vendor/usexp/src/usexp.ml", line 243, characters 6-150
Called from file "src/sexp.ml", line 57, characters 16-28
Called from file "src/import.ml", line 464, characters 8-11
Re-raised at file "src/import.ml", line 466, characters 30-37
Called from file "src/jbuild_load.ml", line 162, characters 8-60
Called from file "src/jbuild_load.ml", line 224, characters 23-44
Called from file "map.ml", line 315, characters 19-42
Called from file "src/jbuild_load.ml", line 234, characters 16-58
Called from file "src/main.ml", line 26, characters 13-56
Called from file "bin/main.ml", line 484, characters 7-29
Called from file "vendor/cmdliner/src/cmdliner_term.ml", line 27, characters 19-24
Called from file "vendor/cmdliner/src/cmdliner.ml", line 106, characters 32-39
Called from file "vendor/cmdliner/src/cmdliner.ml", line 136, characters 18-36
Called from file "vendor/cmdliner/src/cmdliner.ml", line 251, characters 22-48
Called from file "bin/main.ml", line 1089, characters 10-51
$ cat test/jbuild
(executables
 ((names (test))
  (libraries (alcotest typebeat))
))

(alias
((name    runtest)
  (deps    (test.exe)
  (action  (run ${<}))))
```

**Comment by rgrinberg** [comment] 2018-01-07 18:39
This is a duplicate of #384

**Closed by rgrinberg** 2018-01-07 18:39 UTC
