### ISSUE TITLE
compiler options that are only compatible with some versions

### ISSUE THREAD

**Issue by c-cube** [janestreet/jbuilder#235] opened 2017-08-25 11:56 UTC
It would be super useful to be able to specify options that are only applied when the compiler support them. OCamlbuild typically does that with custom `_tags` entries. Such options include, non exhaustively:

- `-color always`
- `-O3` and similar flambda options such as `-unbox-closures`

**Comment by dra27** [comment] 2017-08-25 13:32
Duplicate of #90

**Closed by dra27** 2017-08-25 13:32 UTC
